#! /bin/python

from optparse import OptionParser
import psutil

parser = OptionParser()
parser.add_option("-n", "--numcpu",action="store_true", dest="numcpu",
                  default=False, help="Print the number of CPU Cores")
parser.add_option("-c", "--cpu",action="store_true", dest="cpu",
                  default=False, help="Print the CPU Percentage")
parser.add_option("-l", "--load",
                  action="store_true", dest="loadavg", default=False,
                  help="Print the load Average of the CPU")
parser.add_option("-s", "--stream",
                  action="store_true", dest="stream", default=False,
                  help="Continuosly stream the values")

(options, args) = parser.parse_args()
try:
    if options.ensure_value('numcpu',False):
        print("CPU Core",psutil.cpu_count())
    if options.ensure_value('cpu',False):
        if options.ensure_value('stream',False):
            while 1:
                print("\rCPU Percentage",psutil.cpu_percent(1),"%",end="")
        print("CPU Percentage",psutil.cpu_percent(1),"%")
    if options.ensure_value('loadavg',False):
        if options.ensure_value('stream',False):
            while 1:
                print("\rLoad Average of CPU",psutil.getloadavg(),end=" ")
        print("Load Average of CPU ",psutil.getloadavg())
except KeyboardInterrupt:
    pass
