#! /bin/python
from multiprocessing import shared_memory
from lib.Argument import Argument
import sys
args = Argument(sys.argv)

if(not args.hasOptions(['--shm', '--pname'])):
    print("Usage: {} --shm=NAME --ptype=[master|slave]".format(sys.argv[0]))
    exit(1)

if(args.getOptionValue('--pname')=='master'):
    shm = shared_memory.SharedMemory(name=args.getOptionValue('--shm'),create=True,size = 1024)
    
else:
    shm = shared_memory.SharedMemory(name=args.getOptionValue('--shm'))

def writeshm(shm,data):
    buff = shm.buf
    buff[:len(data)] = bytearray(data,'utf-8')

def readshm(shm):
    buff = shm.buf
    return str(buff,'utf-8').rstrip('\x00')

while True:
    choice = input('1: Read SHM; 2: Write SHM; Choose > ')
    if choice == '1':
        print(readshm(shm))
    elif choice == '2':
        val  = input("Enter a string to write to SHM > ")
        writeshm(shm,val)
